import { defineRouting } from 'next-intl/routing'
import { localeConfig } from './config'

/**
 * i18n Routing Configuration
 * 
 * Enforces URL-based locale routing:
 * - /ar/... for Arabic
 * - /en/... for English
 * 
 * Locale resolution order:
 * 1. URL prefix
 * 2. Stored preference (cookie/localStorage)
 * 3. Browser language
 */

export const routing = defineRouting({
  // Supported locales
  locales: localeConfig.locales,
  
  // Default locale (from config)
  defaultLocale: localeConfig.defaultLocale,
  
  // Locale detection strategy
  localeDetection: true,
  
  // Locale prefix strategy
  localePrefix: 'always', // Always show locale in URL: /ar/... or /en/...
})

// Export types for use in components
export type Locale = (typeof localeConfig.locales)[number]

// Re-export Next.js generated route types for validator
// These types are generated by Next.js in .next/types/routes.ts
// and are re-exported here to satisfy the validator file
export type {
  AppRoutes,
  LayoutRoutes,
  ParamMap,
} from '../.next/types/routes'
